# Generated by Django 4.2.7 on 2025-09-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0003_sellerprofile_sellerproduct_sellerinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
