# Generated by Django 4.2.7 on 2025-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0004_company_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerinvoice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sellerproduct",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
