# Generated by Django 4.2.7 on 2025-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productanalytics",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
