# Generated by Django 4.2.7 on 2025-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_order_orderitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinvoice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
